### ISSUE TITLE
Simple and easy to understand

### ISSUE THREAD

**Issue by aaron-elkins** [skx/simple.vm#14]
Your byte code design is pretty elegant, I love this

```
        store #1, 1982
        store #2, "Good byte code design!"
```

And love the implementation behind the sence.

Thanks for showing this kind of VM, forked.

**Comment by skx** [comment]
Thanks for the kind words :)

If I were doing it again I'd keep things mostly the same, but instead I'd make sure that strings were not inline, and then that would allow me to keep all instruction-lengths the same.  Maybe three bytes long, always.  Allowing:

    op, src1, src2, dest

Or some other arrangement.  In cases where tehre didn't need to be four bytes we'd just pad with a 0x00.  (The strings would go in a string-table at the end of the program.)
