### ISSUE TITLE
Segmentation Faults 2017-05-14

### ISSUE THREAD

**Issue by rwhitworth** [skx/simple.vm#21]
Found a few more bad inputs that cause segmentation faults.  Though not all of them seg fault under valgrind, which I'm still trying to figure out.  They can be found https://github.com/rwhitworth/simple.vm-fuzz/tree/master/2017-05-14 if you're interested.  Thanks for the quick fixes this weekend.

**Comment by skx** [comment]
Thanks for more input!   I've only looked at two of them, but both were issues with bounds-checking on the stack (which is fixed/static at 1024 entries).   Suspect the bugfixs I did last night will resolve them all once I push.

(I didn't say, but I'm also running my own fuzz-testing and I hope it'll have a completed a cycle or two by the time I return home from work :) )

**Comment by rwhitworth** [comment]
`or [send me a donation](https://steve.fi/donate/)`

Well played.

**Comment by skx** [comment]
Fuzzing seems to be going well ..

![afl](https://cloud.githubusercontent.com/assets/735291/26076707/47acc886-39c2-11e7-8642-d33f22befe86.jpg)

**Comment by rwhitworth** [comment]
Is that 5024 executions a second without any special changes made to simple-vm source?  If so, you may want to use afl-clang-fast to compile, and then add something like

```
  while (__AFL_LOOP(1000)) {
    parse(argv[1]);
  }
```

This change should improve the fuzzing speed.  Not that 5024 executions isn't fast already :-)

More detail on blogs like this one: https://foxglovesecurity.com/2016/03/15/fuzzing-workflows-a-fuzz-job-from-start-to-finish/

**Comment by skx** [comment]
Yup that's an average speed on this system, it varies a little depending on the programs that it is being fed - but not hugely.

Thanks for the pointer, in the past I've tweaked input (e.g. when fuzzing redis) but I mostly forget about it.  My usual approach to fuzzing is to either run fuzzing in the background, on my desktop, over the course of a week or so, or use a bunch of virtual machines and run a lot of tests across hardware, independently.
